// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBomWLQLJ_ZUX_ut2q5zPbHMHoG9IeZLxA',
    appId: '1:1099365248426:web:573bcbaf795ef7ccb2cfd3',
    messagingSenderId: '1099365248426',
    projectId: 'prikitiw-18dde',
    authDomain: 'prikitiw-18dde.firebaseapp.com',
    databaseURL: 'https://prikitiw-18dde-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prikitiw-18dde.firebasestorage.app',
    measurementId: 'G-C58E1BF3KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoa1q7feSQngEZv1oSniXMuUPTiJsPkPE',
    appId: '1:1099365248426:android:a5cc4500695aa46db2cfd3',
    messagingSenderId: '1099365248426',
    projectId: 'prikitiw-18dde',
    databaseURL: 'https://prikitiw-18dde-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prikitiw-18dde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJhxFVTNtZ3myjC0l8Y3lkiZbNQyGmKCU',
    appId: '1:1099365248426:ios:754f5a966e9214d6b2cfd3',
    messagingSenderId: '1099365248426',
    projectId: 'prikitiw-18dde',
    databaseURL: 'https://prikitiw-18dde-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prikitiw-18dde.firebasestorage.app',
    iosBundleId: 'com.example.pirotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJhxFVTNtZ3myjC0l8Y3lkiZbNQyGmKCU',
    appId: '1:1099365248426:ios:754f5a966e9214d6b2cfd3',
    messagingSenderId: '1099365248426',
    projectId: 'prikitiw-18dde',
    databaseURL: 'https://prikitiw-18dde-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prikitiw-18dde.firebasestorage.app',
    iosBundleId: 'com.example.pirotech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBomWLQLJ_ZUX_ut2q5zPbHMHoG9IeZLxA',
    appId: '1:1099365248426:web:6f1960fd33dae92db2cfd3',
    messagingSenderId: '1099365248426',
    projectId: 'prikitiw-18dde',
    authDomain: 'prikitiw-18dde.firebaseapp.com',
    databaseURL: 'https://prikitiw-18dde-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prikitiw-18dde.firebasestorage.app',
    measurementId: 'G-S0RL8QFVG4',
  );
}
